apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare

resources:
- namespace.yaml
- configmaps.yaml
- secrets.yaml
- mongo.yaml
- postgres.yaml
- patient-service.yaml
- appointment-service.yaml
- medical-records-service.yaml
- rbac.yaml

commonLabels:
  project: healthcare-microservices
  environment: base

images:
- name: healthcare/patient-service
  newTag: latest
- name: healthcare/appointment-service
  newTag: latest
- name: healthcare/medical-records-service
  newTag: latest